name: memfast
description: "Memfast"

publish_to: 'none' 
version: 1.5.0+8

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  #backend
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

  #googleads
  google_mobile_ads: ^6.0.0

  #navigation
  go_router: ^17.0.1 

  

  #local database
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  #permission
  permission_handler: ^12.0.1

  #model
  equatable: ^2.0.7

  #state managment
  flutter_bloc: ^9.1.1
 
  #firestore
  cloud_firestore: ^6.0.3

  #network_manager
  connectivity_plus: ^7.0.0

  #url-pop-update
  url_launcher: ^6.3.2

  #animation
  animated_text_kit: ^4.3.0

  #fonts
  google_fonts: ^6.3.2

  
  just_audio: ^0.10.5

  #assets
  flutter_svg: ^2.2.3
  easy_localization: ^3.0.7

  #short-code
  kartal: ^4.2.0
  package_info_plus: ^8.3.1

  


  cupertino_icons: ^1.0.8
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #RUNNER  
  build_runner: ^2.5.4

  #Assets
  flutter_gen_runner: ^5.12.0
  
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/
    - assets/icons/
    - assets/musics/
    - assets/lottie/
    - assets/musics/
  #   - images/a_dot_ham.jpeg

 
