name: memfast
description: "Memfast"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.3.0+3

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #backend
  firebase_core: ^2.24.2  
  #googleads
  google_mobile_ads: ^4.0.0  
  #local database
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  #model
  equatable: ^2.0.5
  #state managment
  flutter_bloc: ^8.1.3
 
  #firestore
  cloud_firestore: ^4.13.6
  #network_manager
  connectivity_plus: ^5.0.2
  #url-pop-update
  url_launcher: ^6.2.2
  #animation
  animated_text_kit: ^4.2.2
  #fonts
  google_fonts: ^6.1.0
  #audioplayer
  audioplayers: ^5.0.0
  just_audio: ^0.9.36
  #assets
  flutter_svg: ^2.0.9
  #short-code
  kartal: ^3.5.0
  package_info_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  lottie: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/musics/
  #   - images/a_dot_ham.jpeg

 
